## Common opensearch configuration parameters ##

os_cluster_name: os-cluster

# opensearch download
os_download_url: https://artifacts.opensearch.org/releases/bundle/opensearch

# opensearch version
# 3.x Latest Version
os_version: "3.2.0"

# opensearch dashboards version
# 3.x Latest Version
os_dashboards_version: "3.2.0"

# Configure hostnames for opensearch nodes
# It is required to configure SSL
# Example es1.example.com, es2.example.com: will be added to inventory_hostname
# e.g os1.domain.internal
domain_name: domain.internal

# Java memory heap values(GB) for opensearch
# You can change it based on server specs
# Max 31
xms_value: 31
xmx_value: 31
java_pkg: openjdk-21-jdk
java_home: /usr/lib/jvm/java-21-openjdk-amd64
java_home_local: /opt/homebrew/Cellar/openjdk/23.0.2/libexec/openjdk.jdk/Contents/Home

# Cluster type whether its single-node or multi-node
cluster_type: multi-node

# opensearch user info
os_user: opensearch

os_dashboards_user: opensearch-dashboards

# Number of days that certificates are valid
cert_valid_days: 3650

# Auth type: 'internal' or 'oidc' (OpenID). Default: internal
auth_type: internal
# auth_type: oidc

# OIDC settings
oidc:
  description: "Authenticate via IdP"
  # OpenID server URI
  connect_url: https://gitlab.com/.well-known/openid-configuration
  # The JWT token field that contains the user name
  subject_key: preferred_username
  # the JWT token field that contains a list of user roles
  roles_key: roles
  # Scopes
  scopes: "openid profile email"
  # The address of Dashboards to redirect the user to after successful authentication
  dashboards_url: https://kibana.miriyev.ai
  # IdP client ID
  client_id: "{{ lookup('bitwarden.secrets.lookup', '0e6d8c47-1672-48dc-af58-b2de009c2b9a') }}"
  # IdP client secret
  client_secret: "{{ lookup('bitwarden.secrets.lookup', '02c00ca3-7d70-45f3-aa72-b2de009c478f') }}"

# Overwrite demo configurations with your own
copy_custom_security_configs: false

# To override demo configurations, you can use your own configuration files.
# Place them in the "files" directory. Specify the path to the files
custom_security_plugin_configs:
  - files/tenants.yml
  - files/roles.yml
  - files/roles_mapping.yml
  - files/internal_users.yml

# By default, if the /tmp/opensearch-nodecerts directory with certificates
# exists on the server from which the playbook is launched, it is assumed
# that the configuration has not changed and some settings are not copied
# to the target servers.
#
# Conversely, if the /tmp/opensearch-nodecerts directory does not exist on
# the server from which the playbook is launched, then new certificates and
# settings are generated and they are copied to the target servers.
#
# If you use this repository not only for the initial deployment of the
# cluster, but also for its automatic configuration via CI/CD, then new
# certificates will be generated every time the pipeline is launched,
# overwriting existing ones, which is not always necessary if the cluster is
# already in production.
#
# When iac_enable enabling, and all the cluster servers have all the necessary
# certificates, they will not be copied again. If at least on one server (for
# example, when adding a new server to the cluster) if there is not at least one
# certificate from the list, then all certificates on all cluster servers will
# be updated
#
# Also, if the option is enabled, the settings files will be updated with each
# execution (previously, the settings were updated only if the
# /tmp/opensearch-nodecerts directory was missing on the server from which the
# playbook was launched and new certificates were generated)
iac_enable: false
